name: Deployment

on:
  push:
    branches:
      - main

jobs:
  deployment:
    runs-on: ubuntu-2gb-hel1-2
    environment: 
      name: production
      url: https://sinimustaahallitustavastaan.org/

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run Deployment Script
        run: |
          # Add your Git pull and service start commands here
          sudo cd /root/smhv_website/
          sudo git pull
          sudo systemctl restart website  # Replace with your service start command
      - name: Deployment Complete
        run: echo "Deployment to production environment completed."
