name: Sync Dev with Main

on:
  schedule:
    - cron: '0 0 * * 1'  # Schedule this workflow to run daily
    
  push:
    branches:
      - main

  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Git
        run: git config --global user.email "sinimustaahallitustavastaan@sinimustaahallitustavastaan.org" && git config --global user.name "Sinimustaa hallitusta vastaan"

      - name: Fetch Main
        run: git fetch origin main

      - name: Check for Changes in Main
        id: check_main
        run: |
          git diff --name-only main origin/main > changed_files.txt
          if [ -s changed_files.txt ]; then
            echo "Changes detected in Main branch."
            echo "::set-output name=changes::true"
          else
            echo "No changes detected in Main branch."
            echo "::set-output name=changes::false"
          fi

      - name: Sync Dev with Main
        if: steps.check_main.outputs.changes == 'true'
        run: |
          git checkout dev
          git merge main
          git push origin dev
